### ISSUE TITLE
댓글 기능 추가

### ISSUE THREAD

**Issue by ryuni-dev** [Pseudo-Lab/data-engineering-for-everybody#23]
* [https://jupyterbook.org/en/stable/interactive/comments/utterances.html](https://jupyterbook.org/en/stable/interactive/comments/utterances.html) 을 참고하여 댓글 기능 추가

**Comment by heehehe** [comment]
앗 경륜님 제쪽에서는 https://pseudo-lab.github.io/data-engineering-for-everybody/intro.html 나 다른 페이지에서 댓글 부분이 보이지 않아서요ㅠㅠ..!
혹시 댓글 부분 잘 확인되실까요?!

혹시 몰라서 https://github.com/apps/utterances 에서 저희 repo에 utterances 설치했는데도 계속 나오지 않는 것 같네요🤔
![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/41580746/3e7983f9-bfb1-48bf-ae2c-b49d2b288808)

**Comment by ryuni-dev** [comment]
엇 이상하네요ㅜㅜ [중간에 cd쪽 충돌난게 있어서](https://github.com/Pseudo-Lab/data-engineering-for-everybody/actions/runs/5495757308) 그땐 댓글 기능이 반영 안 된게 맞고... [방금 배포한 버젼에선 반영되어야 하는데](https://github.com/Pseudo-Lab/data-engineering-for-everybody/actions/runs/5497340958)..! 이건 다시 한번 알아보겠습니다!🥹

**Comment by heehehe** [comment]
(개인적으로 궁금해서 한번 살펴본 내용 기록해둡니다! 해결은.. 못했습니다🥲)

저희 가짜연구소 Tutorial-Book repo에서는 아래 링크처럼 반영해뒀더라고요..!
https://github.com/Pseudo-Lab/Tutorial-Book/blob/f3027782726a892e1a246deeca14f61ffe9063c9/book/_config.yml#L41-L48

뭔가 `issue-term: "pathname"`도 수정해줬어야 하는 부분이라
여기 때문에 문제가 생긴건 아닌가 싶어서 지우고 위 링크처럼 해봤지만..
여전히 안되네요 😭

***

제 개인 repo에 utterances 설치 후에 [setup 관련 페이지](https://utteranc.es/?installation_id=39992730&setup_action=install)가 나오면서 이런 부분이 있었는데요..!
![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/41580746/eb1e9b37-fc52-4e35-920f-646bf6d75f0d)

한번 메인 페이지에 추가해서 진행해보고 있습니다!!
~이게 성공한다면 저희 repo에는 `book/intro.md`에 이렇게 추가해두면 될 것 같아요!~ 추가해도 여전히 나오지 않는군요😂😂..
```
<script src="https://utteranc.es/client.js"
        repo="Pseudo-Lab/data-engineering-for-everybody"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

테스트했던 페이지 혹시 몰라서 남겨둡니다!
https://heehehe.github.io/data-engineering-for-everybody/intro.html
