### ISSUE TITLE
cloud computing and data engineering --> 8강으로 당기기

### ISSUE THREAD

**Issue by yesinkim** [Pseudo-Lab/data-engineering-for-everybody#26]

**Comment by Steve-YJ** [comment]
@yesinkim 안녕하세요 예신님! #41  태스크와 겹치는 부분이 있어서 제가 해결하는게 조금 더 수월 할 것 같습니다! 제가 8강 미업로드분 업로드함과 동시에 9->8로 변경해도 될까요?

**Comment by yesinkim** [comment]
@Steve-YJ 네! 당연하죠! 작업하신 거 확인했습니다 :) 저는 나머지 문서 업로드 진행하겠습니다

**Comment by Steve-YJ** [comment]
해당 이슈는 #41 과 함께 처리하도록 하겠습니다. 
Issue Close 하겠습니다!
