### ISSUE TITLE
요약/정리, 실습 등 컨텐츠 이모티콘으로 구분 표시

### ISSUE THREAD

**Issue by heehehe** [Pseudo-Lab/data-engineering-for-everybody#28]

**Comment by ehddnr301** [comment]
정리: 📝 
실습: 💻 

으로 넣어볼까 하는데 괜찮으실지 궁금합니다. 앞에넣을지 뒤에넣을지는 넣어보면서 봐야알것같습니다ㅎㅎ;;

**Comment by yesinkim** [comment]
![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/83568823/1d43561a-bfb7-4841-936a-c8baf75d9c7a)
---
7강에 동욱님이 올려주신 목차 부분인데, 개인적으로 이 형태가 가독성이 좋아보여 마음에 듭니다 :)

**Comment by ehddnr301** [comment]
![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/54092915/9ac6bae6-40df-4af2-8378-38bf621f0c97)

테스트 해보고 있는데 저는 이모지를 전부 넣어놓으니 조금 과한가..? 하는 생각이 들어서 실습부분에만 추가해두고 📝 이모지는 추후에 의견을 모아 수정해봐도 좋을 것 같습니다.

**Comment by ehddnr301** [comment]
#64
