### ISSUE TITLE
README 개선

### ISSUE THREAD

**Issue by heehehe** [Pseudo-Lab/data-engineering-for-everybody#31]
- [ ] 스터디 중심으로 내용 정리 (진행 목차 추가 등)
- [ ] gitbook 링크 추가 (이미지 등으로)

**Comment by Steve-YJ** [comment]
아직 이슈에 해당하는 작업을 시작하지 못했습니다…! 주말을 이용해서 드래프트 버전 공유드리도록 하겠습니다!

## 예상 작업 내역
- [ ]  gitbook 링크 추가 (이미지 등으로)
- [ ] 스터디 중심으로 내용 정리 (진행 목차 추가)
- [ ] 구성원 소개 및 링크

## 참고 저장소
[nerf 스터디 저장소](https://github.com/Pseudo-Lab/nerds-nerf)
[인과추론 스터디 저장소](https://github.com/CausalInferenceLab/Causal-Inference-with-Python)
