### ISSUE TITLE
[session-4.1] 페이지 구성 변경

### ISSUE THREAD

**Issue by heehehe** [Pseudo-Lab/data-engineering-for-everybody#44]
- [x] 소개하듯이 어투 변경
- [x] 4.1 / 4.2 구분 없애기
    - 다른 세션들과 통일해서 지금 4.1 -> 4.1.1, 4.1.2, ... 되어 있던 구분을 4.1, 4.2, 4.3, ... 으로 푸는 것이 좋을 것 같습니다!
    - as-is
      ![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/41580746/b282e416-5bf1-48eb-98d5-60dacf7e6714)
    - to-be
      ![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/41580746/03b67b78-4e92-4d29-ac6c-2d09171fc8da)

**Comment by ehddnr301** [comment]
![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/54092915/8d547082-d13f-46bb-b89e-85e42b888eca)

이 형태가 의도하신 형태가 맞을까요?

**Comment by heehehe** [comment]
> 이 형태가 의도하신 형태가 맞을까요?

오 네네 맞습니다 감사합니다ㅎㅎ!
4강 뒷부분 database 부분만 챕터 하나로 합칠까 싶기도 한데요..🤔
이 부분은 한번 고민해보고 변경하게 되면 따로 PR 올릴게요! :)
