### ISSUE TITLE
Python 세부주제 선정

### ISSUE THREAD

**Issue by heehehe** [Pseudo-Lab/data-engineering-for-everybody#6]
- [x] 세부주제 정리
- [ ] 세부주제 논의

***

#### (참고) DataCamp 내 Python 관련 강의
- Efficient Python Code
- Writing Function in Python
- Unit Testing for Data Science in Python
- OOP(Object-Oriented Programming) in Python

**Comment by Steve-YJ** [comment]
@heehehe 희선님 주제 선정해주셔서 감사합니다! 
데이터 캠프 내에서 중요한 주제들을 선정해주셨네요! 기대됩니다ㅎㅎ

주제 선정 관련해서 한 가지 문의드립니다.
주제별로 하위 카테고리가 따로 나뉘는건가요?
(e.g. Efficient Python Code라는 주제 아래에 하위 주제들이 나뉘는지)

저는 데이터 캠프의 강의를 참고해서 해당 주제에서 중요하다고 생각되는 부분을 하위 주제로 잡았습니다.
e.g. 
- Your first database
    - Introduction to relational databases 
    - Tables: At the core of every database
    - Update your database as the structure changes
  
시작 전에 너무 세세하게 주제를 잡아놓으면 지칠수도 있을 것 같다는 생각도 들고요...ㅎㅎ
우선은 큰 주제만 잡고 하나씩 채워가는 과정에서 세부 주제들을 정하는 방법도 괜찮을 것 같다는 생각입니다 :)
의견 주시면 감사하겠습니다!

**Comment by heehehe** [comment]
@Steve-YJ 
헛 영전님 남겨주셨던 코멘트를 이제야 확인했네요..!😭

저 일단 datacamp에서 중요하다고 생각이 들었던 챕터들이랑 업무하면서 많이 쓰였던 라이브러리 위주로 정리해봤어요!
https://www.notion.so/chanrankim/2d8ae18781934d05a13aa3c6675b2c30?v=fef2976524024fc0a9972538aa629b29&p=96d4e829c0d94fe4b2bf302eb7b8912f&pm=s

추후 앞쪽 <kbd>Fundamentals</kbd>에는 datacamp 내용 위주로 담고
뒤쪽 <kbd>Libraries</kbd>에는 패키지별로 자주 사용되는 스니펫처럼 작성해보려고 생각하고 있었는데요,

시간 편하실 때 한번 살펴보시고 의견 주시면 감사하겠습니다ㅎㅎ!

**Comment by heehehe** [comment]
@Steve-YJ 영전님 저희 이전에 만들어뒀던 issue들은 close 해두겠습니다 :)
